[package]
name = "axum-cookie"
version = "0.1.0-alpha"
edition = "2021"
description = "Cookie extractor middleware for axum"
license = "MIT"

[dependencies]
axum = "0.8"
cookie-rs = "0.2"
tower-layer = "0.3"
tower-service = "0.3"
